---
- name: Check Uptime of Linux Systems
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Run uptime command
      shell: uptime -p
      register: uptime_output
      ignore_errors: true

    - name: Extract uptime line
      set_fact:
        uptime_line: "{{ uptime_output.stdout | default('NOT_FOUND') }}"

    - name: Show uptime
      debug:
        msg: "System uptime is: {{ uptime_line }}"
