---
- name: Check Timezone of Linux Systems
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Run timedatectl to get timezone info
      shell: timedatectl --no-pager
      register: timezone_output
      ignore_errors: true

    - name: Extract timezone line candidates
      set_fact:
        timezone_line_candidates: "{{ timezone_output.stdout_lines | select('search', 'Time zone') | list }}"

    - name: Pick first timezone line (if exists)
      set_fact:
        timezone_line: "{{ timezone_line_candidates[0] if timezone_line_candidates | length > 0 else 'NOT_FOUND' }}"

    - name: Parse timezone (if line found)
      set_fact:
        timezone: "{{ timezone_line.split()[2] if ' ' in timezone_line else 'UNKNOWN' }}"

    - name: Show timezone
      debug:
        msg: "Timezone is: {{ timezone }}"
